### PR TITLE
Data Science

### PR DESCRIPTION
**Pull request by syedbilal5000**
### Please check if this PR fulfills these
- [x] The commit message is descriptive of changes
- [x] You have tried at least one local test (this includes viewing the changes on your local fork)
- [x] Docs have been added / updated as needed (for bug fixes / features) 

### What kind of change does this PR introduce? 

- [ ] Typo / Doc Update
- [ ] Bug Fix 
- [x] Feature / New Item

### What is the new behavior (if this is a feature change)?

- [x] Added Interview Technical Question
- [ ] Added Interview Whiteboard Question
- [ ] Corrected existing items
- [ ] Other

### CODE REVIEW

**Comment by LukeSchlangen** [comment]
This is great! Could you add a link from the `technical.html` to your new page? Right now, there is no link, so people would have to guess the url. This should just require adding an `<a>` tag to the `technical.html` page.

**Comment by syedbilal5000** [comment]
I added the link.

**Comment by LukeSchlangen** [comment]
Thanks! Could you update the link to say something like `Data Science Overview` instead of `Link 1`? The `Link 1` text is a placeholder.

**Comment by LukeSchlangen** [comment]
Perfect! Thank you!

**Comment by syedbilal5000** [comment]
Welcome.

**Pull request merged**
