### PR TITLE
Round out OOP questions!

### PR DESCRIPTION
**Pull request by andyvh**
### Please check if this PR fulfills these
- [x] The commit message is descriptive of changes
- [x] You have tried at least one local test (this includes viewing the changes on your local fork)
- [x] Docs have been added / updated as needed (for bug fixes / features) 

### What kind of change does this PR introduce? 

- [x] Typo / Doc Update
- [ ] Bug Fix 
- [x] Feature / New Item

### What is the new behavior (if this is a feature change)?

- [x] Added Interview Technical Question
- [ ] Added Interview Whiteboard Question
- [ ] Corrected existing items
- [ ] Other

### Other information:

I added two more questions, and elaborated on Objects vs Classes!

### CODE REVIEW

**Comment by LukeSchlangen** [comment]
The inheritance title say `polymorphism`. I just merged another PR into master, could you update your branch to resolve the conflicts? Thank you for doing this!

**Comment by LukeSchlangen** [comment]
Thanks @andyvh! Are you familiar with how to resolve merge conflicts? Because other changes have been added to the project, there are now conflicts when we merge. In order for this to work smoothly, we have to fix the `views/technical.html` file. Are you comfortable/do you want to take a crack at doing that?

**Comment by andyvh** [comment]
Yep, I can do that! Might be a bit though, I have a prior commitment this evening...

**Comment by andyvh** [comment]
Sorry, I got a little tangled up in that... Ready now though!

**Comment by LukeSchlangen** [comment]
No problem! Thanks for all the work you put into this!

**Pull request merged**
