### PR TITLE
Andys questions

### PR DESCRIPTION
**Pull request by andyvh**
### Please check if this PR fulfills these
- [x] The commit message is descriptive of changes
- [x] You have tried at least one local test (this includes viewing the changes on your local fork)
- [x] Docs have been added / updated as needed (for bug fixes / features) 

### What kind of change does this PR introduce? 

- [ ] Typo / Doc Update
- [ ] Bug Fix 
- [x] Feature / New Item

### What is the new behavior (if this is a feature change)?

- [x] Added Interview Technical Question
- [ ] Added Interview Whiteboard Question
- [ ] Corrected existing items
- [ ] Other

### CODE REVIEW

**Comment by LukeSchlangen** [comment]
Encapsulation is a great one! Thank you!

**Comment by andyvh** [comment]
I can round out the other major OOP points too, if you like!

Andy Van Heuit
(925) 283-9719 (Home) | (925) 787-0818 (Cell)
advanheuit.com

**Comment by LukeSchlangen** [comment]
@andyvh That would be great if you wanted to round out the other OOP technical questions!

(I removed your comment because personal information like phone numbers shouldn't be on here. Anyone could abuse it or spam your phone.)

**Comment by andyvh** [comment]
Thank you! Sorry about that, it's part of my email signature, and I forgot that it'd be appended to the comment if I commented via email...

**Comment by LukeSchlangen** [comment]
No sweat, we're all learning, it's pretty unlikely anyone else caught it in the time it was up. Again, thanks for being a part of this project!

**Pull request merged**
