### PR TITLE
Adds a technical question

### PR DESCRIPTION
**Pull request by wiardvanrij**
Adds a technical question and updates the technical overview to include the link towards the answer. 

Used the 'paragraph' tags in the URL's so the links will be shown in a nice 'list'.

Relates to #30

### CODE REVIEW

**Comment by LukeSchlangen** [comment]
I think concatenation is a great addition! Since code is included, I would recommend moving this to the `whiteboard` questions. If you take a peek at the `fizz-buzz` example, mentioning the language and utilizing the show and hide will make it so people can try it themselves first (without being tempted to peek at your solution).

Also, if you could update the `<title>` and `h1` tags, then I think I'll be able to merge it in! Cool to have a command line example.

**Comment by wiardvanrij** [comment]
Should be ok now I guess

**Comment by ziyadedher** [comment]
You should change the `<title>` to Concatenate and the `<h1>` tag as well.

**Comment by LukeSchlangen** [comment]
Perfect! Thank you so much @wiardvanrij and @ziyadedher!

**Pull request merged**
