### PR TITLE
added a new technical question 

### PR DESCRIPTION
**Pull request by nvinayvarma189**
### Please check if this PR fulfills these
- [x] The commit message is descriptive of changes
- [x] You have tried at least one local test (this includes viewing the changes on your local fork)
- [x] Docs have been added / updated as needed (for bug fixes / features) 

### What kind of change does this PR introduce? 

- [ ] Typo / Doc Update
- [ ] Bug Fix 
- [x] Feature / New Item

### What is the new behavior (if this is a feature change)?

- [x] Added Interview Technical Question
- [ ] Added Interview Whiteboard Question
- [ ] Corrected existing items
- [ ] Other

### CODE REVIEW

**Comment by nvinayvarma189** [comment]
Added a new and interesting question as I thought that might have good chance of being asked in a interview

**Comment by nvinayvarma189** [comment]
added another question

**Comment by nvinayvarma189** [comment]
added another question

**Comment by LukeSchlangen** [comment]
Looks good!

**Pull request merged**
