### PR TITLE
added example to recursion.html

### PR DESCRIPTION
**Pull request by nvinayvarma189**
I thought an example of recursion would help others to understand about it better

### Please check if this PR fulfills these
- [x] The commit message is descriptive of changes
- [x] You have tried at least one local test (this includes viewing the changes on your local fork)
- [x] Docs have been added / updated as needed (for bug fixes / features) 

### What kind of change does this PR introduce? 

- [x] Typo / Doc Update
- [ ] Bug Fix 
- [x] Feature / New Item

### What is the new behavior (if this is a feature change)?

- [ ] Added Interview Technical Question
- [ ] Added Interview Whiteboard Question
- [x] Corrected existing items
- [ ] Other

### CODE REVIEW

**Comment by LukeSchlangen** [comment]
Thanks! I like the example, but it should probably be moved out of the `footer`. Could you make that change?

**Comment by nvinayvarma189** [comment]
I did not understand what you want.Can you explain me please

**Comment by LukeSchlangen** [comment]
Sure! It looks like the tag added was added inside the footer tag? I'd like to keep the `footer` tag the same throughout the entire project, so I think the code snippet here should be moved up and out of the footer. Right now it looks like this:

```HTML
    <footer>
        <hr>
        <p class="text-container">An
            <a href="https://github.com/approachable-io/welcome">Approachable Open Source</a> project from
            <a href="http://www.approachable.io">Approachable IO</a>
        </p>
        <p>Here is an example code to calculate the power of a number provided with the exponent</p>
        <pre>
          def power(base,exp):
              if(exp==1):
                  return(base)
              if(exp!=1):
                  return(base*power(base,exp-1))
          base=int(input("Enter base: "))
          exp=int(input("Enter exponential value: ")
          print("Result:",power(base,exp))
        </pre>
    </footer>
```

**Comment by LukeSchlangen** [comment]
Fixed in another PR!

**Pull request closed without merging**
